name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

env:
  # The version we want to pull https://oracle.github.io/macaron/pages/installation.html#download
  # Main implies latest.
  MACARON_TAG: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Macaron
        run: |
          # Ideally we would want to cache the docker image. This would be a TODO-
            curl -O https://raw.githubusercontent.com/oracle/macaron/${{ env.MACARON_TAG }}/scripts/release_scripts/run_macaron.sh
            chmod +x run_macaron.sh
            ./run_macaron.sh 
            echo "Macaron version: ${{env.MACARON_TAG}} installed"


      - name: Sanity Check
        run: ./run_macaron.sh --help
