name: CI

on:
  push:
    branches:
      - "NORUN"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

env:
  # The version we want to pull https://oracle.github.io/macaron/pages/installation.html#download
  # Main implies latest.
  MACARON_TAG: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Macaron
        run: |
          # Ideally we would want to cache the docker image. This would be a TODO-
            curl -O https://raw.githubusercontent.com/oracle/macaron/${{ env.MACARON_TAG }}/scripts/release_scripts/run_macaron.sh
            chmod +x run_macaron.sh
            # You have to do --help here. Simply putting ./run_macaron.sh for the initial run will yield error code 64 and fail the build process
            # See: https://github.com/neilscallywag/macaron-test/actions/runs/14510714862/job/40708546519
            ./run_macaron.sh --help
            echo "Macaron version: ${{env.MACARON_TAG}} installed"

      - name: Sanity Check
        run: ./run_macaron.sh --help
