name: Maven Release with SLSA Provenance

on:
  release:
    types: [created]

jobs:
  release:
    outputs:
      artifacts-sha256: ${{ steps.hash.outputs.artifacts-sha256 }}
      version: ${{ steps.extract_version.outputs.version }}

    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Extract release version
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Release version: $VERSION"

      - name: Update version in pom.xml
        run: |
          mvn versions:set -DnewVersion=${{ steps.extract_version.outputs.version }} -DgenerateBackupPoms=false

      - name: Build and deploy locally to create artifacts for SLSA provenance
        id: deploy
        run: |
          mkdir -p $HOME/.m2/local-repository
          mvn clean package -Dmaven.test.skip=true
          GROUP_ID=$(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout | sed 's/\./\//g')
          ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
          echo "group=$GROUP_ID" >> $GITHUB_OUTPUT
          echo "artifact=$ARTIFACT_ID" >> $GITHUB_OUTPUT

      - name: Debug artifact generation
        run: |
          echo "Checking for artifacts in target directory..."
          ls -la target

      - name: Find artifacts in local repository
        id: find_artifacts
        run: |
          VERSION=${{ steps.extract_version.outputs.version }}
          ARTIFACTS=$(find target -type f \( \( -iname "*.jar" -not -iname "*-javadoc.jar" -not -iname "*-sources.jar" \) -or -iname "*.pom" \))
          if [ -z "$ARTIFACTS" ]; then
            echo "No artifacts found!"
            exit 1
          fi
          echo "Found artifacts:"
          echo "$ARTIFACTS"
          ls -la $ARTIFACTS
          echo "ARTIFACTS=$ARTIFACTS" >> $GITHUB_ENV

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maven-build-outputs
          path: ${{ env.ARTIFACTS }}
          retention-days: 5

      - name: Upload artifacts hash
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-sha256
          path: artifacts-sha256
          retention-days: 5

      - name: Generate documentation
        run: |
          echo "hello world"

  provenance-subject:
    needs: [release]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts-sha256
        uses: actions/download-artifact@v4
        with:
          name: artifacts-sha256

      - name: Set artifacts-sha256 as output
        id: set-hash
        shell: bash
        run: echo "artifacts-sha256=$(cat artifacts-sha256)" >> "$GITHUB_OUTPUT"

  provenance:
    needs: [release, provenance-subject]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    with:
      base64-subjects: "${{ needs.provenance-subject.outputs.artifacts-sha256 }}"
      upload-assets: true
      compile-generator: true

  github_release_artifacts:
    needs: [release, provenance]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: maven-build-outputs
          path: maven-repository

      - name: Create artifacts archive
        shell: bash
        run: |
          VERSION=${{ needs.release.outputs.version }}
          find maven-repository -type f \( -name "*.jar" -not -name "*-javadoc.jar" -not -name "*-sources.jar" -o -name "*.pom" \) | xargs zip -j maven-artifacts-${VERSION}.zip

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          files: maven-artifacts-*.zip
          fail_on_unmatched_files: true